more range loops for modern C++
OGRECave/ogre pull request #2536
Opened 2022-08-01 12:46 UTC by Joilnen

2022-08-01 23:59 UTC, paroj commented on OgreMain/src/OgreAnimationState.cpp
> +                OGRE_EXCEPT(Exception::ERR_ITEM_NOT_FOUND, "No animation entry found named " + s.first, \
```suggestion
                OGRE_EXCEPT(Exception::ERR_ITEM_NOT_FOUND, "No animation entry found named " + s.first,
```
the issue is that the line ends with a whitespace

2022-08-02 00:02 UTC, paroj commented on OgreMain/src/OgreCompositor.cpp
> -                    p != def->formatList.end(); ++p, ++atch)
++atch missing

2022-08-02 00:02 UTC, paroj commented on OgreMain/src/OgreCompositor.cpp
> +                            ResourceGroupManager::INTERNAL_RESOURCE_GROUP_NAME, TEX_TYPE_2D, \
```suggestion
                            ResourceGroupManager::INTERNAL_RESOURCE_GROUP_NAME, TEX_TYPE_2D,
```
as before

2022-08-02 00:26 UTC, Joilnen commented on OgreMain/src/OgreCompositor.cpp
> -                    p != def->formatList.end(); ++p, ++atch)
changed

2022-08-02 12:21 UTC, paroj commented on OgreMain/src/OgreCompositionTechnique.cpp
> +    for (auto& i : mTextureDefinitions)
```suggestion
    for (auto td : mTextureDefinitions)
```

2022-08-02 12:22 UTC, paroj commented on OgreMain/src/OgreCompositionTechnique.cpp
> +    for (auto& pi : mTargetPasses)
```suggestion
    for (auto targetPass : mTargetPasses)
```

2022-08-02 12:22 UTC, paroj commented on OgreMain/src/OgreCompositionTargetPass.cpp
> +    for (auto& passi : mPasses)
```suggestion
    for (auto pass : mPasses)
```

2022-08-02 12:24 UTC, paroj commented on OgreMain/src/OgreAnimationTrack.cpp
> +            if (i != *mKeyFrames.begin() &&
this now compares the element instead of the iterator, which changes behaviour. I think you have to leave the loop as is.

2022-08-02 12:25 UTC, paroj commented on OgreMain/src/OgreAnimationState.cpp
> +        for (auto& s : mEnabledAnimationStates)
```suggestion
        for (auto src : mEnabledAnimationStates)
```

2022-08-02 12:26 UTC, paroj commented on OgreMain/src/OgreAnimationState.cpp
> +        for (auto& s : rhs.mEnabledAnimationStates)
```suggestion
        for (auto src : rhs.mEnabledAnimationStates)
```

2022-08-02 12:26 UTC, paroj commented on OgreMain/src/OgreAnimationState.cpp
> +        for (auto& s : rhs.mAnimationStates)
```suggestion
        for (auto src : rhs.mAnimationStates)
```

2022-08-02 12:28 UTC, paroj commented on OgreMain/src/OgreCompositor.cpp
> +    for (const auto& texDefIt : tdefs)
```suggestion
    for (auto def : tdefs)
```

2022-08-02 12:30 UTC, paroj commented on OgreMain/src/OgreAnimationTrack.cpp
> +                if (k == *mKeyFrames.begin())
revert this as well. (element vs. iterator comparison)

2022-08-02 12:31 UTC, paroj requested changes
iterator comparison must not change

2022-08-02 22:24 UTC, paroj commented
I realised that reviewing this is very error-prone as I might miss some iterator/ element comparison change.

Therefore, I ran clang-tiny to automatically do this conversion where applicable. The results are being built in #2538

Therefore I would close this for now. Sorry for the inconvenience.

2022-08-02 22:24 UTC, closed without merging