range loop refactoring
OGRECave/ogre pull request #2630
Opened 2022-10-16 20:25 UTC by Joilnen

2022-10-23 01:04 UTC, paroj commented on OgreMain/src/OgreMeshSerializerImpl.cpp
> +            // numSubs = pMesh->getNumSubMeshes();
commented code

2022-10-23 01:04 UTC, paroj commented on OgreMain/src/OgreMeshSerializerImpl.cpp
> +                // SubMesh* sm = pMesh->getSubMesh(i);
commented code

2022-10-23 01:06 UTC, paroj commented on OgreMain/src/OgreMeshSerializerImpl.cpp
> +            while (bass)
why not for?

2022-10-24 16:29 UTC, paroj commented on OgreMain/src/OgreMeshSerializerImpl.cpp
> +            while (bass)
@Joilnen

2022-11-06 00:39 UTC, paroj commented on OgreMain/src/OgreMeshSerializerImpl.cpp
> +            while (bass)
this one is still outstanding

2022-11-06 12:05 UTC, paroj requested changes
the while loop should be change to for

2022-11-06 16:56 UTC, Joilnen commented
backing to normal *for*, *range for* rise not used variable compile errors in some builds

2022-11-06 18:20 UTC, Joilnen commented
> the while loop should be change to for

did

2022-11-06 18:30 UTC, merged