Use all available processor cores to build dependencies
OGRECave/ogre pull request #2801
Opened 2023-03-03 14:06 UTC by markellus

Building dependencies like SDK2 and assimp currently takes an unnecessary long time, because they do not use all available processor cores. With this patch, the number of available cores is automatically detected and passed to the dependency CMake scripts. This makes the build process about 2-3 times faster on my 12 Core processor when using MinGW-w64.

2023-03-08 09:48 UTC, paroj requested changes

2023-03-08 09:48 UTC, paroj commented on CMake/Dependencies.cmake
> +ProcessorCount(N)
```suggestion
ProcessorCount(NPROC)
```

2023-03-10 12:53 UTC, paroj commented on CMake/Dependencies.cmake
> +set(BUILD_COMMAND_OPTS --target install -j ${N} --config ${CMAKE_BUILD_TYPE})
```suggestion
set(BUILD_COMMAND_OPTS --target install -j ${NPROC} --config ${CMAKE_BUILD_TYPE})
```

2023-03-10 12:54 UTC, paroj commented on CMake/Dependencies.cmake
> +if(N EQUAL 0)
```suggestion
if(NPROC EQUAL 0)
```

2023-03-10 12:54 UTC, paroj commented on CMake/Dependencies.cmake
> +    set(N 2)
```suggestion
    set(NPROC 2)
```

2023-03-10 16:27 UTC, merged

2023-03-17 20:16 UTC, markellus commented
Hi, sorry I was not able to make changes in the last week, but I see everything is resolved already 👍